variables:
  DOCKER_REPOSITORY: mendersoftware/deviceconnect

stages:
  - test
  - build
  - publish

include:
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-golang-static.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-golang-unittests.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-apidocs.yml'

test:static:
  image: golang:1.14

test:unit:
  image: golang:1.14
  services:
    - mongo
    - nats
  variables:
    DEVICECONNECT_MONGO_URL: "mongodb://mongo"
    DEVICECONNECT_NATS_URI: "nats://nats:4222"
