# API server listen address
# Defauls to: ":8080" which will listen on all avalable interfaces.
# Overwrite with environment variable: DEVICECONNECT_LISTEN

listen: :8080


# NATS uri
# Defauls to: "nats://localhost:4222"
# Overwrite with environment variable: DEVICECONNECT_NATS_URI

# nats_uri: "nats://localhost:4222"
