openapi: 3.0.3

info:
  title: Device Connect
  description: |
    Device facing API for managing persistent device connections.

  version: "1"

  contact:
    name: Mender Support
    email: support@mender.io
    url: https://mender.io/contact-us

  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: https://hosted.mender.io/api/devices/v1/deviceconnect

# Global security definitions
security:
  - DeviceJWT: []

tags:
  - name: DevicesAPI

paths:

  /connect:
    get:
      tags:
        - DevicesAPI
      operationId: Connect
      summary: >
        Connect the device and make it available to the server.
      description: >
        Calling /connect will upgrade the connection to a persistent
        websocket connection and making the device available to the
        management api. The device must provide it's identity using
        the DeviceJWT either as Authorization header or as a cookie named
        'JWT'.
      parameters:
        - in: header
          name: Connection
          schema:
            type: string
            enum:
              - Upgrade
          description: Mandatory websocket request header
        - in: header
          name: Sec-Websocket-Key
          schema:
            type: string
            format: base64
          description: Standard websocket request header.


      responses:
        101:
          description: |
            Successful response - change to websocket protocol.
          headers:
            Sec-Websocket-Accept:
              schema:
                type: string
                format: base64
              description: Standard websocket upgrade response header.
            Upgrade:
              schema:
                type: string
                enum:
                  - websocket

        400:
          $ref: '#/components/responses/InvalidRequestError'
        500:
          $ref: '#/components/responses/InternalServerError'


components:
  securitySchemes:
    DeviceJWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        JWT token issued by 'POST /api/devices/v1/authentication/auth_requests'

  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: Description of the error.
        request_id:
          type: string
          description:
            Request ID passed with the request X-MEN-RequestID header
            or generated by the server.
      description: Error descriptor.
      example:
        error: "<error description>"
        request_id: "eed14d55-d996-42cd-8248-e806663810a8"


  responses:
    InternalServerError:
      description: Internal Server Error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: "internal error"
            request_id: "eed14d55-d996-42cd-8248-e806663810a8"

    InvalidRequestError:
      description: Invalid Request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: "bad request parameters"
            request_id: "eed14d55-d996-42cd-8248-e806663810a8"
